name: FortressPlugin
main: me.newyith.fortress.main.FortressPlugin
version: 0.1
author: NewYith
  
commands:
  fort:
    description: Commands to manage your fortress.
    usage: /fort stuck - Teleports you away
  fort stuck:
    description: Teleports you away after a delay.
    usage: /fort stuck
  test:
    description: Test command for debugging
    usage: /<command>
