package me.newyith.fortress.protection;

import me.newyith.fortress.util.Point;
import org.bukkit.World;

import java.util.Set;

//TODO: maybe move responsibility for bedrock ripple and particles (CoreParticles) here
//	except particles need to appear only on the outside
//	and bedrock ripple should only search points currently generated by generator
public class ProtectionManagerForWorld {

	public ProtectionManagerForWorld(World world) {

	}

	public Set<Point> protect(ProtectionBatch protectionBatch) {
		return null;
	}

	public Set<Point> unprotect(ProtectionBatch lastOldProtectionBatch) {
		return null;
	}

	public boolean isProtected(Point p) {
		return false;
	}
}
